### ISSUE TITLE
Switch on Dimmer

### ISSUE THREAD

**Issue by trentyounggit** [jbasen/Crestron-Shelly#12]
Hi there, I grabbed your Shelly dimmer module. Thanks heaps for that. Is there an option on the dimmer for for the switch input/button to come into the crestron module? Or do I just use a 'button' module pointed to the same device/ip?

**Comment by jbasen** [comment]
Hmmm.  Good question.  I just hadn't thought about including button press outputs on that module.  Your idea of trying to use the button module in parallel with the same IP address isn't a bad one and might work.  Same for trying one of the relay modules that also has button press outputs.  It might work but then again without trying it I can't be sure as I've never tried it before.  I will put it on the the list of things to do to add outputs for the different button presses directly to the dimmer module.  Let me know if using a button or relay module in parallel (same IP address) works as a work around until I get a time to add that feature. 

Thanks

**Comment by trentyounggit** [comment]
Thanks. I emailed back but not sure if it came through
I haven't used Shelly before but might order a dimmer and relay and have a play around.
Thanks

**Comment by jbasen** [comment]
Button press outputs have been added to the dimmer module in v12 of the Shelly demo program.
Thanks

**Comment by trentyounggit** [comment]
Awesome thanks!



Trent Young
Acts Global Churches
0408 559 082

Sent from my iPhone

On 14 Jul 2022, at 2:34 am, jbasen ***@***.***> wrote:

﻿

Button press outputs have been added to the dimmer module in v12 of the Shelly demo program.
Thanks

**Comment by trentyounggit** [comment]
Thanks
I haven’t bought or used an Shelly yet but was looking at using some in my home.
I might order a relay and a dimmer to play around with.


Trent Young
Acts Global Churches
0408 559 082

Sent from my iPhone

On 24 Jun 2022, at 12:40 am, jbasen ***@***.***> wrote:

﻿

Hmmm. Good question. I just hadn't thought about including button press outputs on that module. Your idea of trying to use the button module in parallel with the same IP address isn't a bad one and might work. Same for trying one of the relay modules that also has button press outputs. It might work but then again without trying it I can't be sure as I've never tried it before. I will put it on the the list of things to do to add outputs for the different button presses directly to the dimmer module. Let me know if using a button or relay module in parallel (same IP address) works as a work around until I get a time to add that feature.

Thanks
