### ISSUE TITLE
porblem with brighnes feedback

### ISSUE THREAD

**Issue by Simjabentzvi** [jbasen/Crestron-Shelly#13]
we follow al the istructiones and never get any feedback at all, 
please let us know what are can we do to be able to have analog fedback
we are using to test the shelly a CRESTRON din-ap3

**Comment by Simjabentzvi** [comment]
sorry the problem is with a SHELLY DIMMER 2
we see the analog feedback in CRESTRON DEBUGGER, BUT WE ARE NOT ABLE TO  get the value in the analog output ¨( Dimmer_Brithness_FB) of your module  we are using SHELLY DIMMER V4
![image](https://user-images.githubusercontent.com/104401685/182512752-b185f0a0-b98a-40d8-8ed2-c8cb8c591195.png)
![image](https://user-images.githubusercontent.com/104401685/182512842-c08f8823-83d2-4e13-b4d5-f9d0b39d67fb.pn g)

**Comment by Simjabentzvi** [comment]
![image](https://user-images.githubusercontent.com/104401685/182513261-dd9babbc-3d00-462b-8ade-44936f539f7a.png)

**Comment by jbasen** [comment]
Fixed in v15
