### ISSUE TITLE
Shelly Uni Analog Inputs

### ISSUE THREAD

**Issue by trentyounggit** [jbasen/Crestron-Shelly#15]
Hey Jason.
Thanks for work on these modules! I just got into Shelly and Crestron integration over the weekend and was really surprised at the lack of latency and quite easy to use.
Im just planning my install and wondering if you have an option for the Shelly Uni to receive the analog inputs voltage? I would like to monitor the 0-10v for possible a daylight or wind sensor.
Or would this be an issue due to the need for lots of polling?

**Comment by jbasen** [comment]
I haven’t worked with the Uni very much. I’ve done much more work with some of the other modules. My experience has been that you won’t have issues unless you go crazy with polling.  

That being said it sounds like you are trying to create a DIY weather station. You can certainly go that route but I also have a module for the Weatherflow Tempest weather station.  That may be a better overall solution for you.  It does wind speed, Lux, and much more. 

Jay

**Comment by trentyounggit** [comment]
Thanks Jason. The Weatherflow would be great option but about $800 AUD so a bit out of my budget for a 'nice' thing to add to the system.
At the moment the UNI crestron module doesn't have the analog inputs coming to it. Could you add it when you are doing something else?
Thanks Trent

**Comment by jbasen** [comment]
Hi Trent,

First, its just Jay.  

I can look at adding the analogs to the module for the uni.   However, I can't promise when that will be.  I just put out new version that supports all the new devices that Shelly released.  

I have included all the source code; including the S# code on my GitHub so if you feel adventurous you can add the features you want yourself.  

Thanks

**Comment by trentyounggit** [comment]
Sorry Jay
Thanks for your time. I'll consider my options

**Comment by jbasen** [comment]
No problem. 

Just so I’m clear you are looking for the module to report readings from the ADC input on the Uni.  Wire number 3 on the diagram shown here:

https://shelly.cloud/products/shelly-uni-smart-home-automation-device/

Correct?

thanks

**Comment by jbasen** [comment]
You got lucky.  I had a bug report on a problem with the shelly EM so I added some code that should support this.  The new uni module is in the v17 test version.  Let me know if this works for you.

**Comment by trentyounggit** [comment]
That is correct with the analog input.
Thanks heaps! I have a UNI on the way so will play around. Appreciate it!
