### ISSUE TITLE
Reading negative values on the Shelly 3EM

### ISSUE THREAD

**Issue by BreNet** [jbasen/Crestron-Shelly#16]
First of all, thank you for the great work so far! I use several Shelly 3EM and have a PV system connected. Thus, it often comes to negative values. These are not interpreted correctly by your Crestron modules.

**Comment by BreNet** [comment]
Sure, here the output:

Shelly_EM_Read_Power_Meter_0
Shelly - Get_Power - Device_IP = 192.168.16.180, Username = , Password = , Power_Meter_Type = 0
Shelly - Get_Power - URL: http://192.168.16.180/emeter/0/power
Shelly EM - EventHandler - Read_Meter_0

Shelly_EM_Read_Power_Meter_1
Shelly_EM_Read_Power_Meter_2
Shelly_EM_Read_Power_Meter_3
Shelly - Get_Power - Device_IP = 192.168.16.180, Username = , Password = , Power_Meter_Type = 0
Shelly - Get_Power - URL: http://192.168.16.180/emeter/2/power
Shelly - Get_Power - Device_IP = 192.168.16.180, Username = , Password = , Power_Meter_Type = 0
Shelly - Get_Power - URL: http://192.168.16.180/emeter/1/power
Shelly EM - EventHandler - Read_Meter_1

Shelly EM - EventHandler - Read_Meter_0

Shelly EM - EventHandler - Read_Meter_3

Shelly - Get_Power - ContentString = {"power":-225.05,"pf":-0.34,"current":2.81,"voltage":231.78,"is_valid":true,"total":1604510.4,"total_returned":243091.5}
Shelly - Get_Power - power = -225.05
Shelly EM - EventHandler - Error Obtaining Power from Meter 0

Shelly - Get_Power - ContentString = {"power":-227.83,"pf":-0.48,"current":2.05,"voltage":233.35,"is_valid":true,"total":680781.7,"total_returned":831961.9}
Shelly - Get_Power - power = -227.83
Shelly EM - EventHandler - Error Obtaining Power from Meter 1

Shelly - Get_Power - ContentString = {"power":18.56,"pf":0.50,"current":0.16,"voltage":233.89,"is_valid":true,"total":420023.3,"total_returned":0.0}
Shelly - Get_Power - power = 18.56
Shelly_EM_Power_Meter_2_FB
Shelly_EM_Read_Power_Meter_0
Shelly_EM_Read_Power_Meter_1
Shelly_EM_Read_Power_Meter_2

Many thanks!
Marten

**Comment by jbasen** [comment]
Perfect. Thanks

**Comment by jbasen** [comment]
I've uploaded a special v17 test version that I hope will address this.  Let me know

**Comment by BreNet** [comment]
Hello,

thank you for the work, unfortunately it was not yet quite successful. The negative values are not output with sign but as maximum value (65535) minus the actual value, so 65355d instead of -180:

Shelly_EM_Power_Meter_0_FB = 80d
Shelly_EM_Power_Meter_1_FB = 65355d
Shelly_EM_Power_Meter_2_FB = 18d

**Comment by jbasen** [comment]
You are treating the value as an unsigned integer instead of a signed integer.  -180 is equivalent to 65356 when viewed as an unsigned integer.  You can validate this in simpl debugger by changing the signal display format of your signal from unsigned integer to signed integer
