### ISSUE TITLE
Relay_0_On turning outlet off

### ISSUE THREAD

**Issue by gerrybags** [jbasen/Crestron-Shelly#17]
Hey Jbasen,

I found a small bug at line 603 in "Shelly Relay v4.usp" module where the Relay_0_On command is just setting it to off

was
myShelly.Send_Relay_Command(Device_IP, 0, 0, "", "");

changed to
myShelly.Send_Relay_Command(Device_IP, 0, 1, "", "");

Works great after this small fix. Just wanted to share so you can update for others! 

Thanks for making this module and keep up the great work!

**Comment by jbasen** [comment]
Thanks. I’ll make the correction and it will be included in the next release

Thanks again

**Comment by jbasen** [comment]
I thought this important enough that I uploaded a new version with the bug fixed - v18.  Thanks again for reporting this
