### ISSUE TITLE
Dimmer v5 Compile Issue

### ISSUE THREAD

**Issue by trentyounggit** [jbasen/Crestron-Shelly#20]
Hi Jay,
I have just started using Dimmer v5 and getting compile errors from SIMPL. I have checked with Dimmerv4 and that compiles fine. See attched compile log.
I dont know much about SIMPL+ so couldn't fault find any further.

[Shelly Dimmerv5 compile logfile.txt](https://github.com/jbasen/Crestron-Shelly/files/9829473/Shelly.Dimmerv5.compile.logfile.txt)

**Comment by trentyounggit** [comment]
And issues with the UNIv3 also
<img width="666" alt="Screen Shot 2022-10-20 at 10 46 31 pm" src="https://user-images.githubusercontent.com/108052608/196940123-9b5d5dc2-bc94-47f8-b0f8-82859bc635ac.png">

**Comment by jbasen** [comment]
I'm sorry, I can't reproduce this.  The compile of both modules works fine for me.  Couple of things to try
First, validate that you have the right Shelly.clz file.  The one you want is in the bin\release folder of the S# zip file and should be dated 10/6/2022.  Validate that you don't have multiple copies of the Shelly.clz file in different directories that might be causing the wrong one to be used the compile.  Also, you can try deleting your .ush files and everything in your SPIsWork folder.  Hope this helps

**Comment by trentyounggit** [comment]
hey mate. Thanks heaps. It was the .clz file. When I updated to the new v5 usp files, I just copied them into the Plus directory. All working now. Thanks
