### ISSUE TITLE
Shelly Duo bulb white balance

### ISSUE THREAD

**Issue by micdre** [jbasen/Crestron-Shelly#22]
Hi,

Is it possible to add a anlogue in/out in the Dimmer V2 module to adjust the white balance on a Shelly Duo bulb?

Kind regards, Michel

**Comment by jbasen** [comment]
Hi Michel,

I can look at adding this in.  It will be a little while until it gets done.  I am in the middle of some other additions to the code and have to finish all that work before any other changes can be released.

Thanks

**Comment by micdre** [comment]
Hi,

Would be great!
I'm in no rush.

The Shelly-Crestron modules i'm using from you working great. Learned a lot of the S# modules.

Met vriendelijke groet,
With kind regards,
Michel Drenthen
Op 31 okt. 2022, om 03:48, jbasen ***@***.******@***.***>> schreef:

Hi Michel,

I can look at adding this in. It will be a little while until it gets done. I am in the middle of some other additions to the code and have to finish all that work before any other changes can be released.

Thanks

**Comment by jbasen** [comment]
Hi Michel,

I have a version you can test that includes white balance.  However, because I'm in the middle of some other changes I'm no able to fully release this yet.  However, here is something you can test with.

https://1drv.ms/u/s!AjlldUMTB6AFgoFzlOcgYIyGS6b2nw?e=LCjRcW

Let me know if you run into any issues with this.

Thanks

**Comment by jbasen** [comment]
FYI - You will have to upgrade to a new version of the relay module if you try this version.  The new code fixes a problem with the relay module that it wasn't initializing the state of inputs to a shelly relay on startup.  To fix this required new parameters on the relay module as well as changes to the parameters passed to s#.  So the new clz is not backwards compatible with earlier versions of the relay module.

**Comment by micdre** [comment]
Tested the new Dimmer V2 (V21) module with a Shelly Duo. 
On/Off/Toggle + feedback: good
DImer /with-balance + feedback: good
Poll: good

**Comment by jbasen** [comment]
THANKS!

**Comment by jbasen** [comment]
This is now included in v21 that I just posted.  Thanks
