### ISSUE TITLE
Add-on temp sensor in shelly 1PM

### ISSUE THREAD

**Issue by antodng** [jbasen/Crestron-Shelly#25]
Hi Would it be possible to add the temperature and humidity parameters via the add-on installed directly on the shelly 1pm?

**Comment by jbasen** [comment]
Hi,,

There is a module titled "Shelly Plus 1 Plus 1PM Add-On v1" already included in v21 of the Shelly modules here on GitHub.  This module works in parallel with the Shelly relay module (just include the IP address of the Shelly device with add-on attached in both modules".    I thought this a better solution then burdening the already large relay module with all the xtra signals needed to support the Shelly Add-On.

Thanks
