### ISSUE TITLE
Shelly Plus HT Webhook changes automatically

### ISSUE THREAD

**Issue by Stefan101980** [jbasen/Crestron-Shelly#28]
Hi everyone! 

First of all I wanna say thank you for the great modules and the possibility to bring both (Shelly and Crestron) together.

but in the last days I had an issue with the webhook that is needed, to report the temperature (same with the humidity) from the Shelly plus HT to the module in the Crestron control system.
According to the help file of the plus ht in simpl windows, the link, given to the plus ht in the webhook settings, should end with something like „${..C}“ if you wanna send the temp in Celsius degrees. If you fill that into the webhook settings, the plus ht changes this automatically to „$temperature“ and Crestron doesn’t receive the value. Is it possible, that this „token“ has changed? Maybe because of firmware updates done by Shelly?

Thanks in advance for your support and have a nice weekend

**Comment by jbasen** [comment]
I'm not aware of any change made by Shelly in this area.  But, that doesn't mean they haven't made a change.  The API documentation still states that ${ev.tC} should include the temperature in Celsius in the webhook url.  That documentation is located here: 

https://shelly-api-docs.shelly.cloud/gen2/ComponentsAndServices/Webhook/

Please remember that the Crestron code requires a "/" character at the end of the webhook url to properly parse the temperature / humidity so the url would be in the form

http://[Processor_IP]:[Processor_Port]/plus-ht/sensor/temperature/${ev.tC}/

For the fastest resolution, I would suggest you contact Shelly directly with the issue you are seeing as opposed to waiting for me to get a plus H&T sensor setup, validating I can reproduce the problem, and the contacting Shelly.  I'll leave this issue open so you can report back what you find and if there is something I need to change on the Crestron side.  Thanks

**Comment by Stefan101980** [comment]
Hey guys,

Shelly support now told me, that both tokens (${ev.tC}/ and $temperature/) should work. The first one should send both (C & F) and select C afterwards, the first one should send directly the temperature in C. 
They haven’t heard about an automatically changing token after pressing the „save“ button and reloading the page.

Greetings

Stefan

**Comment by jbasen** [comment]
Thanks for letting me know.  There is nothing I can change on the Crestron driver side for this as it appears to simply be an issue with the UI on the device so I'm going to close the issue.
