### ISSUE TITLE
Brightness Feedback Shelly Vintage

### ISSUE THREAD

**Issue by SchallmeisterMU** [jbasen/Crestron-Shelly#29]
![image](https://user-images.githubusercontent.com/122621727/212344746-0fe853cf-e4f8-4cfb-b88a-14ec65cd3600.png)

Hi,

thank you so much for your work on this project!
I have a problem on getting the brightness feedback from a shelly dimmer (vintage bulb) to the crestron analog signal.
When i poll the the module, the answer shows the correct value in the debugger, but the corresponding analog out shows nothing.
The on/off feedback works great and power consumption feedback from a different shelly device works as well. 
When i send a brightness command to the shelly it works, too.
I'm on latest versions in shelly, crestron and your modules.

Am i missing something?

Thank you very much for your help!

Marcus

**Comment by jbasen** [comment]
Do you have the Device_Gen parameter on the Shelly Dimmer V6 module set to Gen_1 or Gen_2?  It should be set to Gen_1 for a vintage bulb.  This affects the parsing of the content string returned by the bulb when you poll for status.
Thanks

**Comment by SchallmeisterMU** [comment]
Hi, it is on gen 1.

**Comment by jbasen** [comment]
Which Shelly Vintage Bulb are you using?  For some reason the returned JSON from the poll command is in the format found on a Gen2 dimmer device.  I'm not sure if you will have other issues if you try changing the the parameter from Gen 1 to Gen 2 but it is worth a try.
