### ISSUE TITLE
1pm possibility to retrieve information from add-on probes 

### ISSUE THREAD

**Issue by antodng** [jbasen/Crestron-Shelly#3]
Hi,

I noticed that there is no possibility to retrieve data from the temperature probes integrated in the 1pm is this a feature you will add?
Thank you

**Comment by jbasen** [comment]
Sorry, at this time I'm just supporting the standard functionality of the relays.  I do support retrieving temperature/humidity data from probes on the Shelly Uni.  I wrote these modules as part of the article I wrote for Residential Tech Today Magazine (https://restechtoday.com/shelly-smart-home-products-review/).  It is my  understanding that Shelly is working with a firm to develop a complete set of Crestron modules for Shelly products and I expect those will cover all the functionality available in each Shelly product.
