### ISSUE TITLE
Just learning

### ISSUE THREAD

**Issue by mikerin0** [jbasen/Crestron-Shelly#30]
Hi, I am learning Crestron.  Is there a guide on how to implement this module?  I am running SIMPL Windows on a series 3 controller.

**Comment by jbasen** [comment]
The two tools I've provided are the SimplWindows demo program and the help that is built into the modules and can be accessed by pressing the F1 key.  The demo program will provide you with an example of how to initialize the modules.  The help file for the individual modules will explain what all the different signals going into/out of the modules, as well as the parameters on the modules, do.  Your best way of figuring things out is to create a small example program controlling, for example, a single relay (or whatever Shelly device you own).  You can then play with the signals in SimplDebugger to learn how things work.  Hope this helps
