### ISSUE TITLE
Humidity-Temperature Sensor V4 module

### ISSUE THREAD

**Issue by micdre** [jbasen/Crestron-Shelly#33]
Hello,

Is it possible to get an 'alive' (like a watchdog) signal from the Shelly Plus H&T?
I want to use it for heating but want to know if the signal with the H&T is lost for safety.

Kind regards, MIchel

**Comment by jbasen** [comment]
Not that I'm aware of as a watchdog would cut down on battery life.  However, I believe you could implement your own watchdog through writing some custom micro-javascript on the plus H&T.

**Comment by micdre** [comment]
Thanks for your answer.
I won't know how to do that.
But maybe Google is my friend here.

Met vriendelijke groet,
With kind regards,
Michel Drenthen

BlueMail voor Android<https://bluemail.me> downloaden
Op 28 feb. 2023, om 14:44, jbasen ***@***.******@***.***>> schreef:

Not that I'm aware of as a watchdog would cut down on battery life. However, I believe you could implement your own watchdog through writing some custom micro-javascript on the plus H&T.

**Comment by jbasen** [comment]
Take a look at the DIY section of this article I wrote.  There is quite a bit on scripting on Shelly Plus devices

https://restechtoday.com/how-to-automate-the-operation-of-your-smart-home-windows/

hope this helps

**Comment by micdre** [comment]
Thanks. I'm gonna look into it.

Met vriendelijke groet,
With kind regards,
Michel Drenthen
Op 1 mrt. 2023, om 04:22, jbasen ***@***.******@***.***>> schreef:

Take a look at the DIY section of this article I wrote. There is quite a bit on scripting on Shelly Plus devices

https://restechtoday.com/how-to-automate-the-operation-of-your-smart-home-windows/

hope this helps
