### ISSUE TITLE
Trying to figure out the motion sensor module

### ISSUE THREAD

**Issue by mikerin0** [jbasen/Crestron-Shelly#34]
Hi, in the help file for the motion sensor module it states:
1) Motion Detected

This field should be set as follows where Processor_IP and
Processor_Port must match what is set in the Shelly Comm Manager
module.  

http://[Processor_IP]:[Processor_Port]/motion/detected/

Where does that parameter go? 

Thank you for any info you can provide.

**Comment by jbasen** [comment]
In other words if the processor port in the comm manager module is left at the default of 9000 and the IP address of your processor is, for example, 192.168.1.100 then the http statement would be

http://192.168.1.100:9000/motion/detected/

Hope this helps

**Comment by mikerin0** [comment]
Understood but where do I actually type that in?  The motion_detected_fb field won't accept some of those characters so it can't be there.

**Comment by jbasen** [comment]
You need to enter it in the webhook section of the Shelly Motion Detector's web interface or using the Shelly App

**Comment by mikerin0** [comment]
got it, works perfectly.  Thank you.
