### ISSUE TITLE
Timer remaining

### ISSUE THREAD

**Issue by micdre** [jbasen/Crestron-Shelly#35]
Not realy an issue but i'm not sure if it should go in the Pull Requests. or if i even am allowed to change your code. 

I wanted to see the remaming time if a timer in a relay was set. This is also documented in the API.

So I created a 'timer remaining' output on shellly relay and 2.5 devices.
if you have set a timer for a relay you are able to see the remaining time in seconds. 
To see it realtime i also created a digital Poll input.
I've tested this in my home setup and it works.

**Comment by jbasen** [comment]
Thanks @micdre 

I specifically post the source code so if people have unique requirements they can make their own modifications to the code.
