### ISSUE TITLE
Shelly 3EM CH2 power and voltage doesn't work

### ISSUE THREAD

**Issue by disnamic** [jbasen/Crestron-Shelly#39]
Hi,

with the "old" Shelly 3EM Gen1 the power and voltage read does not work on the third channel (Signal "Power_Meter_2_FB")

I found the issue within the Shelly EM v5 Module:
(Device_Type = GEN_1_EM) in the if statements of all CH2 init/push statements is missing.

I've added them and it works fine now. :) 

Thanks for your work on these modules, they are really helpfull! 
Martin

**Comment by jbasen** [comment]
Hi Martin,
Thanks so much for taking the time to find the issue and let me know about it.  I'd greatly appreciate it if you could simply post the code change you made here then I'll be sure to correctly update the module.
Thanks again
Jay

**Comment by disnamic** [comment]
Hi Jay,
my pleasure really.
I've made a diff for you to review:
https://www.diffchecker.com/7ziZagaX/

**Comment by jbasen** [comment]
Thanks @disnamic 

The diff was great.  I've made the change and will get this uploaded in the next day, or so.  There will be other changes in the new version that I hadn't uploaded yet.

Thanks again.
