### ISSUE TITLE
shelly internal temperature

### ISSUE THREAD

**Issue by antodng** [jbasen/Crestron-Shelly#4]
Hi, all shellys have a temperature probe internally to avoid overburn, that would be an interesting data to be able to have on each shelly is a feature you could add please?

Thank you

**Comment by jbasen** [comment]
Sorry, at this time I'm just supporting the standard functionality of the shelly devices needed to use them. I wrote these modules as part of the article I wrote for Residential Tech Today Magazine (https://restechtoday.com/shelly-smart-home-products-review/). It is my understanding that Shelly is working with a firm to develop a complete set of Crestron modules for Shelly products and I expect those will cover all the functionality available in each Shelly product.
