### ISSUE TITLE
Shelly H&T BLU sensor

### ISSUE THREAD

**Issue by micdre** [jbasen/Crestron-Shelly#41]
Hi,

Can you add the Shelly H&T BLU sensor?

Kind regards, Michel

**Comment by micdre** [comment]
Double entry. Sorry

**Comment by jbasen** [comment]
Hi @micdre 
I'm still looking for someone with JavaScript skills to help me implement this.  Adding BLU device support requires custom JavaScript.  The original BLU devices I added support for were done with the assistance from someone at Shelly that is no longer with the company.  Let me know if you know JavaScript and have the time to help.  The scripts done for the other BLU devices would be a starting point for the code needed for the BLU H&T.  Thanks

**Comment by jbasen** [comment]
Closing this and going to the original post on the request
