### ISSUE TITLE
Shelly Roller - EventHandler - Wrong IP - Device_IP = 192.168.10.109, Channel = 0, Roller_State =, Position = 0

### ISSUE THREAD

**Issue by OZEO-DOOZ** [jbasen/Crestron-Shelly#45]
Hello, 

I have migrate on a news version of your driver and now I have a new problem.

Do you know were it came from?

Shelly Roller - EventHandler - Wrong IP - Device_IP = 192.168.10.109, Channel = 0, Roller_State =, Position = 0

**Comment by OZEO-DOOZ** [comment]
Error in this code : 
 
THREADSAFE CHANGE Shade_1_Position
{
	Trace("Shelly Roller - EventHandler - Shade_1_Position = %d\n", **Shade_0_Position**);
	If ((Startup_Lock = 2) && (Cover_Count = 2))
	{
		myShelly.Send_Roller_Command(Device_IP, Device_Gen, 1, 4, **Shade_0_Position,** "", "");
	}
}

**Comment by jbasen** [comment]
Thanks @OZEO-DOOZ .  I have that fixed in my version of the code and it will be put on GitHub the next time I upload the code.
Thanks again.
