### ISSUE TITLE
Action for BLU Door Window

### ISSUE THREAD

**Issue by OZEO-DOOZ** [jbasen/Crestron-Shelly#46]
Hi,

What is the frame for the BLU Door Window? I can not see it in the help.

http://[Processor_IP]:[Processor_Port]/bthome/[Bluetooth_Device_MAC_Address]/??/$value/

**Comment by jbasen** [comment]
I'm not sure what you mean by "frame".  

Unlike other devices, all communications for the blu door / window sensor are handled by the java script code that has to be loaded onto the host shelly device.  So, there is no webhook required.

**Comment by OZEO-DOOZ** [comment]
Hi, Thanks for your reponse. 

I dont understant how proced. The module is in BLE what should I do to get there informations on thé Crestron processor who is on the LAN.

**Comment by jbasen** [comment]
Shelly BLU devices need to be connected to another Shelly device that will act as a gateway between the Bluetooth communications used by the BLU device and the http communications between the gateway shelly device and the Crestron processor.  

Depending on the  BLU device, the proper javascript has to be loaded onto the gateway Shelly device as a script.  In the case of the BLU Door-Window sensor the Bluetooth Door-Window.js file needs to be loaded as a script onto the gateway device.  In addition, the Target IP and Target Port need to be edited in the script to be the IP address of the Crestron processor and the port for communications.  

IMHO Shelly BLU devices are much more complicated to deal with than regular Shelly devices that sit on the network.

Thanks

**Comment by OZEO-DOOZ** [comment]
Thanks for every things. I will test on friday.
