### ISSUE TITLE
Shelly Plus Uni

### ISSUE THREAD

**Issue by P89Tech** [jbasen/Crestron-Shelly#47]
The Shelly Uni has been replaced by the Plus Uni. The current Uni module does not appear to be compatible, specifically the analog / voltage feedback does not seem to work.

Inputs
    Initialize - works
    Channel_0_Output_On - works
    Channel_0_Output_Off - works
    Channel_1_Output_On - works
    Channel_1_Output_Off - works
    Poll_Temp_Humidity - unable to test (don't have a DHT22 or DS18B20 chip)
    Poll_ADC_Voltage - does not work

Outputs
    Channel_0_Button_On_FB - works
    Channel_0_Button_Off_FB - works
    Channel_0_Button_Long_FB - Plus Uni does not appear to support
    Channel_0_Button_Short_FB - Plus Uni does not appear to support
    Channel_0_Output_On_FB - works
    Channel_0_Output_Off_FB - works

    Channel_1_Button_On_FB - works
    Channel_1_Button_Off_FB - works
    Channel_1_Button_Long_FB - Plus Uni does not appear to support
    Channel_1_Button_Short_FB - Plus Uni does not appear to support
    Channel_1_Output_On_FB - works
    Channel_1_Output_Off_FB - works

    Temperature_FB - unable to test (don't have a DHT22 or DS18B20 chip)
    Humidity_FB  - unable to test (don't have a DHT22 or DS18B20 chip)
    Voltage_FB - does not work

Additionally the module does not appear to support the "Count In" function available on the Plus Uni.

Voltage was tested with a potentiometer, the Plus Uni itself read values accurately.

**Comment by jbasen** [comment]
I do not currently have an UNI Plus.  One is required before I can add support for it to the driver set.  Once I get one, it will take quite some time to develop the code as the UNI, with the possible add-ons is one of the more complicated Shelly devices.  In addition, Shelly has plenty of relays, which are supported by the Crestron driver, that can be used in place of an UNI.

**Comment by P89Tech** [comment]
Completely understandable. I was just hoping you might have an easy fix or work around you could suggest for the voltage FB not working. Thanks.

**Comment by jbasen** [comment]
The only suggestion I can make is to do some coding on your own outside of my modules.  According to the Shelly documentation: https://shelly-api-docs.shelly.cloud/gen2/ComponentsAndServices/Voltmeter

if you send the command: http://192.168.33.1/rpc/Voltmeter.GetStatus?id=0

The response you will get is:

{
  "id": 0,
  "voltage": 3.5,
  "xvoltage": 4.5
}

You would have to simply create some code to send the http command to your uni and parse the response.

Thanks

**Comment by P89Tech** [comment]
Thanks for your help. Coding worked fine, except that their example seems unclear when it comes to using the right id.

**Comment by jbasen** [comment]
I completely understand and welcome to my world.  Shelly's API documentation leaves something to be desired and they have so many different versions of products, with different generations of APIs, that without a doubt the Crestron-Shelly driver is the most challenging driver I've written for me to maintain.
