### ISSUE TITLE
Should Shelly Device State Be Visible in Crestron, if Changed Outside Crestron? // Polling Current Shelly Device State?

### ISSUE THREAD

**Issue by waffles0042** [jbasen/Crestron-Shelly#49]
Hello @jbasen ;

I am trying to get a better understanding of the module's capabilities regarding obtaining feedback. 

Feedback seems to be working great as long as I initiate the command via Crestron  (I am trying to control a simple Shelly US Plug), e.g. if I switch the plug to ON, Crestron immediately set the corresponding fb signal to high.
However, I have not been able to have Crestron detect if a Shelly state was changed outside Crestron. Furthermore, there also does not seem to be any Shelly state polling during the initial launch of the module. 
So is what am seeing to be expected/normal or have I not yet configured my setup properly? If the former, is there a change to add this functionality?
TIA!

**Comment by jbasen** [comment]
The mechanism that shelly uses to update driver software of events on a Shelly device are webhooks.  These are http requests that are made by the Shelly device to the IP address of the smart home processor / hub to provide a status update.  If you open the web UI for your smart plug you can find where you can create webhooks.  The help for my modules describes the format for the webhook http requests that my driver code expects to receive when, for example, someone presses the button input on a relay or a relay is closed by something other than a call to the driver code.  Hope this helps

**Comment by waffles0042** [comment]
Thanks @jbasen , I'll check it out.

**Comment by waffles0042** [comment]
I got it working!  With your hint above, the section in the Help File underneath IMPORTANT finally made sense to me. :-)
Thanks much again, @jbasen!
