### ISSUE TITLE
Other Shellys, are you working on modules for them?

### ISSUE THREAD

**Issue by Gizzmo80** [jbasen/Crestron-Shelly#6]
Hi, 

first of all thanks for the Shelly modules, I bought some different devices and I am testing your modules. Today I was happy to see that you made the dimmer2 and RGBW modules too. Integrated them but for me polling didn't work well for my dimmer2. Sometimes I get values, somtimes only 0d, and somtimes the dimmer even switches off. Not shure if it's because at the moment
I don't have a fixture connected. So need to check that. 

I have some other Shellys a Flood, Door 2 and a H&T. So I am wondering if you are working on modules for these devices too. 
Beside these the smoke and gas sensor could be interesting too.

**Comment by jbasen** [comment]
Hi and thanks for your message.  At this point I'm not sure why you would be having problems with the polling trigger on the dimmer2.  I don't have one setup right now so I would have to set it up and do some testing.  That being said, unless you are going to use the Shelly app, or some other control mechanism, in parallel with the Crestron dimmer2 module there is no reason you should ever have to poll the device.  If the device is turned on/off or the dim level set using the Crestron module then the module feedback accurately reflect the status of the dimmer2 .  

The only Shelly sensor I've written code to support is the motion sensor.  I don't have any of the other sensors to develop software and test with at this time.  I can look into that but it will be a while until that happens as I'm trying to make some updates to some of the other software available on my Github.

**Comment by jbasen** [comment]
I had a few minutes and dug out a dimmer2.  I've reproduced the issue and sent a request in to shelly as I don't see anything wrong with the command being sent to poll the status of the dimmer2.  I'll post when I hear something back.

**Comment by jbasen** [comment]
I spoke to the folks at Shelly about the issue with the dimmer2.  Initially they thought it was an API bug.  After some additional testing they realized that the issue is that you MUST go through the dimmer2 calibration process.  That process is mandatory when using the product as you can dim different bulb types and there are significant differences between, for example, dimming an LED vs dimming an incandescent bulb.  Once you go through the calibration process the issue you reported will go away.

Shelly is going to send me some of their sensors so I can add code for them to the driver.  This won't happen immediately but I'll add additional support to the driver as I have time.  

Thanks

**Comment by Gizzmo80** [comment]
Hi, thanks for checking this and talking to Shelly. That was something I thought of. The issue was without a load the dimmer will not calibrate. I connected a load now and will test this later again. 

Did you talk to them about action urls for the values, so polling will not be needed? can/will they add these?

About the additional Shelly, great to read and thank you so much.

**Comment by jbasen** [comment]
Polling shouldn't be needed if you only control the Shelly device through the Crestron-Shelly module.  It is only when you control the device through a second interface (such as the Shelly app) that the Crestron module will get out of synch. 

When I have asked in the past about additional url actions for other shelly devices I was told that will need to wait for Shelly's next generation of products as the memory being used in the current modules is pretty maxed out.

**Comment by Gizzmo80** [comment]
hmm, OK will ask from my side. Let's see what I get :)

So tested it with a load connected and yes polling seems to work. But the light values still seems to behave a little strange. 

Pressing "Output_On" = light goes on and I get the light value, but this value jumps immediately to 0d. 

![shelly_dimmer2_debugger](https://user-images.githubusercontent.com/46043322/125817604-cdb5ba5d-9dd0-4065-ba86-cd8a635df163.jpg)

**Comment by Gizzmo80** [comment]
Checked the RGBW2, there it's the same. 

![shelly_rgbw2_debugger](https://user-images.githubusercontent.com/46043322/125818714-3fe1861f-91e7-4ead-a991-c66e6ecc1cb1.jpg)

**Comment by jbasen** [comment]
Are you using the latest versions of the RGBW2 and Dimmer2 modules that were part of the v7 version of the Shelly demo program that I uploaded last week?  I have setup both a bulb on a dimmer2 and an RGBW light strip on a RGBW2.  I can't reproduce any of the issues you are reporting.  I've been turning lights on/off, pulsing the poll input, changing RGBW levels, and changing brightness. 

The code for the RGBW2 module was very broken in v6 of the demo program and I also made some changes to the code for the dimmer2 as part of the v7 release.  The latest modules for the RGBW2, dimmer2, along with the hubitat.clz file from the v7 demo program all need to be used and earlier versions discarded.

Please let me know if this fixes the problem

**Comment by Gizzmo80** [comment]
Have to check this, but I believe before I had downloaded an older version, I believe there were no dimmer modules included. I downloaded the v7 files and copied them in my database. While doing this the older files should have been overwriten. So should be the new files but will check tomorrow (Germany it‘s 23 o‘clock :)  ).

**Comment by jbasen** [comment]
Thanks.  Any time there are signal changes on a module I update the module's filename and #SYMBOL_NAME.  This allows someone to migrate from the old version of the module to the new version with a drag and drop to copy all the signals and parameters.  It also keeps from having people open a program and have errors that force a resynch.  

However, it does mean that you have to manually check for updated symbols.  Crestron doesn't provide a perfect solution so it is a tradeoff on which approach to take.  

If you are still having problems please make sure that the Startup_Debug_Message_Output parameter is set to Console on the Shelly Comm Manager v1 symbol.  Also please in addition to a Simpldebugger window being open in toolbox that a text console window is open.  I have been seeing a lot of problems where debugging print statements don't show up in the debugger but they will show up in a console window.  Finally, please save the log in simpldebugger and send that along with a copy/paste of the console window to me.  Sending a screen shot of the the debugger cuts off information that I'd like to be able to see.

Thanks

**Comment by jbasen** [comment]
One other thing I thought of.  Please make sure you've changed the #INCLUDEPATH statement in the S+ modules to reflect here you are putting the shelly.clz file.  Also please make sure you don't have a copy of the Shelly.clz file in your usrsplus directory along with the location specified in the includepath.  The compiler could be getting confused as to which Shelly.clz file to use if there are multiple conflicting copies.

Crestron had issues a while back where the compiler couldn't find clz files if they were just put in the usrsplus directory.  The work around was to specify the location in an includepath statement in the S+ file.  I'm not sure if that problem was ever fixed but I've been simply using the includepath ever since.

Thanks

**Comment by Gizzmo80** [comment]
Hi, 
so I never downloaded v6, I was starting with v5 and was surprised and happy to see while testing that there was v7 with the dimmer modules. Because these were missing for me. So yes the RGBWv3 and Dimmerv2 are in my program, these should be 
the latest. When these were copied I took all modules from the demo folder in my splus folder and have overwritten the older modules, so the .clz should be the new one. But now I deleted the .clz file and reinserted it with the file from v7. 

So all modules and the .clz are in my splus folder, there is no module within the project folder. 

To be shure I opened the Dimmerv2 and RGBWv3 modules and did a "recompile all", to be shure if there are errors because of
the includepath or not found .clz and that the modules get linked within the database. There were no errors. Even when the 
includepath was still yours and because of that wrong. 

I always put the .clz in the splus folder, only while testing with O. Hall for a module in beta I used them in the projectfolder. 
This always worked for me, I never saw that it was neccessary to use the includepath. 

So I will test it that way and if it still shows me the issue I will change the includepath. But I believe for compiling Crestron uses
projectfolder, if not there splus folder, if not there but a includepath is set it will check there. Maybe if a includepath is set it 
will check there first and than the other places, but I believe all are checked. Because if the .clz would not have been found the
Shelly control would not have worked at all.

Oh reading again, you mentioned the "hubitat.clz" from v7. Really ? I have the Shelly.clz from v7.

**Comment by Gizzmo80** [comment]
so, still the includepath not changed or commented out it's the same issue. 

I believe you still have a "Trace" within the RGBWv3 module which is not in the dimmerv2. So in console you see more happening. So for RGBWv3 you see a second Traceoutput for EventHandler. There the color values are -1 and gain is 0. 
I would believe this is the same in dimmerv2 but without a trace we don't see it in the log. 

Why are these values -1 for color and effect and gain 0 ? 
Pretty shure Crestron shows the -1 values as 0 and of course the gain 0 is 0.


![shelly_rgbw2_debug+console](https://user-images.githubusercontent.com/46043322/125904800-25ce87ef-2121-4a10-b274-ae78b0965d7f.jpg)

**Comment by Gizzmo80** [comment]
OK, so now I commented out the includepath line and activated Trace for the dimmerv2 module. Both modules show a second traceoutput with all values 0d.  Don't know what could be wrong on my side :)

**Comment by jbasen** [comment]
This is very weird.  There are 2 ways we can proceed.  

1) Take the Shelly demo program v7, comment out all the Shelly folders (Relays, Roller Shutter, etc.) except the Comm Manager and the Dimmer 2 folders.  Then in the comm manager folder open the stepper and comment out all the output signals except Shelly_Dimmer_Init.  Next, go into the initialization folder, open the SR Latch symbol, and comment out the System_Steady_State output signal.  Next, change the Startup_Debug_Message_Output parameter on the Shelly Comm Manager v1 symbol to consoler.  Finally, add the IP address of your Shelly dimmer2 to the parameter field of the dimmer 2 module.  Compile the demo program, load it to your processor, and test it.  This is exactly how I'm testing.  If this works we can then figure out why your program has problems. 

2) Send me a compiled.zip file of your program and I can take a look at it though I probably won't get to it until over the weekend.  You can load it to dropbox, onedrive, etc. and send me a download link.  My email is jay.m.basen@gmail.com

Sorry about the reference to hubitat.clz.  I'm in the middle of making some enhancements to the code I've written to integrate a Hubitat Elevation Hub with a Crestron processor and just have hubitat on my brain.

Thanks

**Comment by Gizzmo80** [comment]
Do you test on series-4 controller or series-3 ? maybe that's a difference. 

So you don't get the values two times? 

Will check the demo programm and report.

**Comment by jbasen** [comment]
I am testing on a 3 series (MC3). I don't get the values changing a second time.  

One other thought.  Is the firmware on your Shelly dimmer 2 up to date?  You can check by connecting to the device's IP address with your browser.  

I can try running the module on a 4 series processor over the weekend.

Thanks

**Comment by Gizzmo80** [comment]
About the Shelly firmware are you on the newest beta or on newest release version?
dimmer2 = 20210429-102101/v1.10.4-g3f94cd7
beta        = 20210702-123207/v1.11.0-rc2-g7766530

same for the RGBW2, there is a beta available, but I am on latest release at the moment. 


I believe I have a DIN-AP3 here, try to check there...

**Comment by Gizzmo80** [comment]
OK, Demoprogram on my MC4 testsystem seems to work. So the question is, what's different here :)

**Comment by jbasen** [comment]
Well I'm relieved to hear that the demo program works on your MC4.  

What you are seeing is correct.  The brightness should go to zero on the dimmer 2 but not on the rgbw2.  That is the way the code is programmed.  The dimmer 2 is much simpler to deal with so I treated it just like a bulb and set the brightness to zero when off.  Given all the other color attributes in the RGBW2 I simply treated the brightness the same way and didn't set it to zero when off.  I realize this isn't consistent but if you want it to work differently you can just play with the S+ code.  

Again, if you want me to take a look at your program I'm glad to do that and I may be able to see what is causing the problem.  The first thing I would look at is if there are any other sources driving the brightness signal in addition to the dimmer2 module. 

Thanks

**Comment by Gizzmo80** [comment]
I believe I found the issue...

Did you setup the I/O Action URLs for ON and OFF, like mentioned in the helpfile?
Or did you leave them off because you only control with Crestron?

It was working on my testsystem, because the I/O Action URLs pointed to the other control system. 
So I changed these to the testsystem controller and now it's fine on my livesystem but the issue is
on my testsystem :)

**Comment by jbasen** [comment]
Interesting.  I hadn't setup I/O action URLs on these because I was only using the Crestron system for control.  I'll be able to try that over the weekend.  Thanks for catching this.

**Comment by Gizzmo80** [comment]
OK, did some more testing and yes switching the I/O Action URLs off solves this issue. At the moment dimmer2 and RGBW2 are working like expected. 

I did some changes to the RGBW2 module about the off state and the values. Not shure if I did it in a clean way but it seems 
to work. Would you like to have this modification to check if you put it in your release?

**Comment by jbasen** [comment]
Thanks. I would definitely like to see the changes you made to the RGBW2
module.

**Comment by jbasen** [comment]
I had some time this afternoon so I did some work on this.  Give this version a try.  There are new dimmer and RGBW S+ modules and a new shelly.clz.  I didn't update the version numbers of the S+ modules because their signal interfaces didn't change.  So, you should be just able to overwrite your previous versions, overwrite the previous clz file, do a recompile all, and upload to your processor. 

The RGBW module will now change the red, green, blue, white, and brightness feedback outputs to zero when it is turned off.

I did test this with url actions setup.

Let me know if this version fixes the problems you saw or if there are any other issues.  Once you validate it works for you I'll post it as the released version.

Thanks

**Comment by Gizzmo80** [comment]
Great, thanks. Where can I download the changed files?

**Comment by jbasen** [comment]
Oops.  My bad.  I could swear I included a download link in my message.  In any case here it is:

https://1drv.ms/u/s!AjlldUMTB6AFgoFBh9qnLLHHZLyaIw?e=gyuDcU

**Comment by Gizzmo80** [comment]
Thank you, I did a short test yesterday. The switching off and value switch to 0 works, great.
But when I activate the I/O Action URLs the brightness value still switches to 0, like before.
For the RGBW2 the color values are fine now when the action urls are on, but for both the 
brightness still shows the issue.


Beside this would it be possible to add the powermeter values to the dimmers and relays
like 2.5 and 1PM?

**Comment by jbasen** [comment]
I have tested using the I/O action urls and have not been able to find any issues.  The problem must be that you are doing something slightly different than I am so we have to find out what that is.  Here is what I am doing.  

1) I am testing using the demo program with everything commented out except for the dimmer 2 module and of course the comm manager module

2) I have my action urls defined as follows:
http://192.168.1.3:9000/dimmer/state/on/
http://192.168.1.3:9000/dimmer/state/off/
I am not using any of the button action urls.  You shouldn't either as they aren't supported by the code.

3) To make the debugger log more readable for you I have turned off Startup_Debug_Msg_Output and commented out the #ENABLE_TRACE statement in the S+ module

4) Here is what I get when I save the debugger log
11:48:02.449: [User Stimulus] : User set //Shelly_Dimmer_Output_Off to Pulse High
11:48:02.527: //Shelly_Dimmer_Output_Off -> 1
11:48:02.590: //Shelly_Dimmer_Output_Off -> 0
11:48:03.230: //Shelly_Dimmer_Output_On_FB -> 0
11:48:03.418: //Shelly_Dimmer_Output_Off_FB -> 1
11:48:03.418: //Shelly_Dimmer_Brightness_FB -> 0d
11:48:03.449: //Shelly_Dimmer_Brightness_FB -> 0d
11:48:07.840: [User Stimulus] : User set //Shelly_Dimmer_Output_On to Pulse High
11:48:07.918: //Shelly_Dimmer_Output_On -> 1
11:48:07.996: //Shelly_Dimmer_Output_On -> 0
11:48:08.043: //Shelly_Dimmer_Output_On_FB -> 1
11:48:08.043: //Shelly_Dimmer_Output_Off_FB -> 0
11:48:08.043: //Shelly_Dimmer_Brightness_FB -> 0d
11:48:08.043: //Shelly_Dimmer_Brightness_FB -> 13100d
11:48:13.761: [User Stimulus] : User set //Shelly_Dimmer_Output_Off to Pulse High
11:48:13.840: //Shelly_Dimmer_Output_Off -> 1
11:48:13.918: //Shelly_Dimmer_Output_Off -> 0
11:48:13.918: //Shelly_Dimmer_Output_On_FB -> 0
11:48:13.918: //Shelly_Dimmer_Output_Off_FB -> 1
11:48:13.918: //Shelly_Dimmer_Brightness_FB -> 0d
11:48:13.949: //Shelly_Dimmer_Brightness_FB -> 0d

5) As you can see.  Each time I pulse the signal to turn off the dimmer the brightness_FB goes to zero.  When I pulse the signal to turn on the dimmer 2 the brightness_FB is restored to the prior setting.  

As I said I just turned off Startup_Debug_Msg_Output and commented out the #ENABLE_TRACE statement to make the debugger log more readable.  

So, what are you doing differently that is causing the issue with the brightness?

Thanks

**Comment by Gizzmo80** [comment]
Thanks, so really strange and still not shure what could be different, beside series-4 controller:

1. Demoprogramv8, commented out everything only dimmer2, RGBW2 and com module
2. activated or deactivated the I/O Action URLs to test (config in attached picture)

![screenshot dimmer2 IO action urrl](https://user-images.githubusercontent.com/46043322/126139396-e0fef647-3a2d-42de-83f0-8e4219adcacd.jpg)

3. commented out the TRACE and deactivated the debug logs

Here is what I get:

0 ms: [User Stimulus] : User set //Shelly_Dimmer_Output_On to Press
16 ms: //Shelly_Dimmer_Output_On -> 1
47 ms: //Shelly_Dimmer_Output_On_FB -> 1
47 ms: //Shelly_Dimmer_Output_Off_FB -> 0
47 ms: //Shelly_Dimmer_Brightness_FB -> 22925d
78 ms: //Shelly_Dimmer_Brightness_FB -> 0d
94 ms: [User Stimulus] : User set //Shelly_Dimmer_Output_On to Release
110 ms: //Shelly_Dimmer_Output_On -> 0
00:04:47.922: [User Stimulus] : User set //Shelly_Dimmer_Output_Off to Press
00:04:47.922: //Shelly_Dimmer_Output_Off -> 1
00:04:47.953: //Shelly_Dimmer_Output_On_FB -> 0
00:04:47.953: //Shelly_Dimmer_Output_Off_FB -> 1
00:04:47.953: //Shelly_Dimmer_Brightness_FB -> 0d
00:04:47.969: //Shelly_Dimmer_Brightness_FB -> 0d
00:04:48.000: [User Stimulus] : User set //Shelly_Dimmer_Output_Off to Release
00:04:48.000: //Shelly_Dimmer_Output_Off -> 0
00:04:51.610: [User Stimulus] : User set //Shelly_Dimmer_Output_On to Press
00:04:51.610: //Shelly_Dimmer_Output_On -> 1
00:04:51.641: //Shelly_Dimmer_Output_On_FB -> 1
00:04:51.641: //Shelly_Dimmer_Output_Off_FB -> 0
00:04:51.641: //Shelly_Dimmer_Brightness_FB -> 22925d
00:04:51.657: //Shelly_Dimmer_Brightness_FB -> 0d
00:04:51.672: [User Stimulus] : User set //Shelly_Dimmer_Output_On to Release
00:04:51.688: //Shelly_Dimmer_Output_On -> 0
00:04:54.969: [User Stimulus] : User set //Shelly_Dimmer_Output_Off to Press
00:04:54.985: //Shelly_Dimmer_Output_Off -> 1
00:04:55.000: //Shelly_Dimmer_Output_On_FB -> 0
00:04:55.000: //Shelly_Dimmer_Output_Off_FB -> 1
00:04:55.000: //Shelly_Dimmer_Brightness_FB -> 0d
00:04:55.016: //Shelly_Dimmer_Brightness_FB -> 0d
00:04:55.063: [User Stimulus] : User set //Shelly_Dimmer_Output_Off to Release
00:04:55.078: //Shelly_Dimmer_Output_Off -> 0


In your log you get first the 0d and after that the correct value when switching on. For me it's the opposite so first I get the
correct value and than the 0d, so for me while using it stays on 0d. 

Not shure how this could be. Try to test with a MC3 now, maybe there is a difference with series-3 and series-4 controller.

**Comment by Gizzmo80** [comment]
OK, tested with MC3 and it seems like with series-3 we get first the 0d and after that the correct value. 
With series-4 (MC4 and AP4) I get first the correct value and than the 0d.

**Comment by Gizzmo80** [comment]
Beside this, another idea. Could you change the dimmer2, RGBW2 modules that way, that if you get a I/O Action URL input (I would believe you get on_fb and off_fb from the Shelly) after that make a poll automatically?

**Comment by jbasen** [comment]
OK.  I'll do some testing on  a CP4 to try and figure out what is going on.

Thanks

**Comment by jbasen** [comment]
It is all based on messages coming from the Shelly device.  My guess is (I won't have time to look at this until later today) that there is simply a timing issue between the 4-series and the 3-series on how these messages are handled.

**Comment by jbasen** [comment]
OK.  I think I have finally fixed this issue.  

Give this a try - https://1drv.ms/u/s!AjlldUMTB6AFgoFC4KlZV0hDlFBFNA?e=BocwwS

The Shelly.clz file is changes as are the s+ files for the rgbw, dimmer, and roller shade.

Let me know if this works for you.

Thanks

**Comment by Gizzmo80** [comment]
Great, thank you for your work on this. 

The first tests seem that the issue is corrected. One question it seems now we only get one brightness value when switching on.
But for switching off there are still two. It's no problem because both values are 0d but could that be changed too, so there is
only one value for off ? It's more a cleanup and reducing unneccessary communication, so should be no big deal if not.

Did you check if a kind of autopolling when the I/O Action URL for on comes in is possible? 
It would be great if we get the correct values when the devices are switched on by Shelly App, so if we can recognize the 
I/O Action URL input, we should be able to do a poll. 
But of course we still don't see value changes from the Shelly app or webinterface, so if both is used we need to poll again
and again.

**Comment by Gizzmo80** [comment]
Not shure if it's a good idea to ask here, but does the Door 2 work for you sending out the digital outputs?

I believe I have setup everything, but I only get the Lux and Temp analog values. I don't get any digital outputs.
Is there something special beside the Action URLs to setup?

For the Door 2 is there a Tilt value to request? it can be setup for Tilt usage, because of that I am asking.


Would it be possible to get for battery powered devices the value of the battery power?

**Comment by jbasen** [comment]
I've uploaded the now released version of v8.  I've tested as best I can with all the devices.  I haven't seen any issue with the door window sensor not reporting open/close events.  That being said, I didn't see it reporting vibration and tilt events though I didn't dig into the settings to see if I simply had something configured wrong.   I have also seen weird issues with the latest Simpldebugger not showing digital signal transitions at times which made debugging this latest release a challenge.  I added support for all the sensors that Shelly provided me with.  

As far as reporting battery voltage, that is a good idea but I believe it would be problematic to implement because there aren't url actions for it and to optimize battery life shelly shuts down communications with the battery operated devices.  So it isn't something that can be polled for and kept up to date.  I will suggest to Shelly that they add an url action for low battery as that would help people keep things operational. 

Thanks

**Comment by Gizzmo80** [comment]
Hi Jay, 
I checked the API and shouldn't the battery value be sent with the values? for H&T for example:

Shelly H&T: MQTT
When configured for MQTT Shelly H&T sends values from its internal sensors on the following topics:

shellies/shellyht-<deviceid>/sensor/temperature: in °C or °F depending on configuration
shellies/shellyht-<deviceid>/sensor/humidity: RH in %
shellies/shellyht-<deviceid>/sensor/battery: battery level in %


This seems the same for alle battery powered devices. Not shure if the MQTT part is something different,
but if the battery value is send with every value report that should be fine.

**Comment by jbasen** [comment]
Crestron processors do not natively support MQTT and I'm not using MQTT for communications between a Crestron processor and Shelly devices.  Instead I use http and url actions.  In your example of a Shelly H&T sensor, the report sensor value url action should be defined as follows for the H&T sensor to report temperature and humidity readings to the Crestron processor

http://[Processor IP Address]:[Processor Port]/ht/sensor/

What the H&T sensor then sends to the crestron processor is

http://[Processor IP Address]:[Processor Port]/ht/sensor/?hum=[Humidity]&temp=[Temperature]&id=shellyht-xxxxxx

The battery level is not included in these message
