### ISSUE TITLE
Sensor(s) only pulse the output

### ISSUE THREAD

**Issue by Gizzmo80** [jbasen/Crestron-Shelly#7]
Hi, 

first of all thanks for the other sensor modules. Now I have Flood, Humidity & Temperature and Door 2 added and tested. 

At the moment I need to check the other sensors, but for Door2 I recognized that the output close and open are only a 
pulse. Did you recognize this? and did you expect a memory logic after the module to hold the state? maybe it would be
better to hold the state within the module.

**Comment by jbasen** [comment]
All the sensors modules pulse the outputs as that is how the events are reported by the Shelly modules.  If you want to, for example, track the open/close status of a door you can easily drive an S-R latch with those signals

**Comment by Gizzmo80** [comment]
Of course that's the way it can be done. OK, so you did recognize it and you expect it to be done external. 
Was not shure you were aware of that, because using these sensors the states need to stay until it changes. 
Because of that maybe it would be better so make the states stay within the module itself. I will think about 
it and maybe try it.

thanks
