### ISSUE TITLE
TRV

### ISSUE THREAD

**Issue by Kraeling** [jbasen/Crestron-Shelly#8]
Hi, are you bringing an update for the TRV?

**Comment by jbasen** [comment]
Hi Kraeling,

I am hoping to have an update for the new Shelly TRV.  I am waiting for Shelly to send me a unit so I can write and test the software.  Once that happens I'll be sure to post the update.  Thanks

**Comment by jbasen** [comment]
I just wanted to let you know that I should have an update to the Shelly code that includes support for the TRV next week.  Thanks for your patience

**Comment by jbasen** [comment]
v9 of the Shelly-Crestron driver has now been posted and supports the TRV.  Thanks
